name: season_core
version: '${version}'
main: me.zehnooo.season_core.SeasonCorePlugin
description: BangCraft SMP Plugin
api-version: '26.2'
load: POSTWORLD
commands:
  season:
    description: Season Description and World Status
    usage: /season
  relic:
    description: Relic admin commands
    usage: /relic <give|check|destroy>